version: '3'

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      target: production
    ports:
      - "5555:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/rsvp_app

  frontend:
    build: 
      context: ./frontend
      target: production
    ports:
      - "8000:8000"
