name: build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: rsvpcontainerregistery.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend container image
        run: |
          cd frontend
          docker build -t rsvp-frontend:latest .
          docker tag rsvp-frontend:latest rsvpcontainerregistery.azurecr.io/rsvp/frontend
          docker push rsvpcontainerregistery.azurecr.io/rsvp/frontend:latest

      - name: Build and push backend container image
        run: |
          cd backend
          docker build -t rsvp-backend:latest .
          docker tag rsvp-backend:latest rsvpcontainerregistery.azurecr.io/rsvp/backend
          docker push rsvpcontainerregistery.azurecr.io/rsvp/backend:latest