name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start containers
        run: |
          docker-compose up -d

      - name: Verify application is accessible
        uses: lakuapik/gh-actions-http-status@v1
        with:
          url: http://localhost:8000
          method: GET
          expected: '[301, 200]'
        continue-on-error: true

      - name: Check HTTP status code
        run: |
          if [ ${{ steps.verify.outputs.status }} == "200" ]; then
            echo "Application is accessible"
          else
            echo "Application is not accessible"
            exit 1
          fi
        env:
          STATUS_CODE: ${{ steps.verify.outputs.status }}