name: Build
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
    types: [opened, synchronize, reopened]
jobs:
  generate_and_checkin_coverage:
    name: Generate and Check-in Coverage
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      # Step 4: Generate coverage reports
      - name: Generate coverage reports
        run: |
          export DATABASE_URL=sqlite:///:memory:
          coverage run -m unittest APIunittest.py
          coverage xml -o coverage.xml
        working-directory: ./backend

      # Step 5: Commit coverage report
      - name: Commit coverage report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase false
          git pull origin main
          git add coverage.xml
          git commit -m "Add backend coverage report"
        working-directory: ./backend
        
      # Step 6: Push changes to the repository
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
